In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import datetime

In [4]:
from collections import Counter
import time
import math
import sys
import datetime
from datetime import datetime
from datetime import timedelta
import collections
from nltk.util import ngrams

In [5]:
df_tenp = pd.read_csv('/data/orlando_2021/csv_files/month_9/done_files/kafka_test_1430.csv')

In [6]:
df_tenp

       signalid                timestamp   eventcode  eventparam
0          1430  2021-09-24 09:00:00.900          43           8
1          1430  2021-09-24 09:00:01.600          81          11
2          1430  2021-09-24 09:00:02.100          82           3
3          1430  2021-09-24 09:00:02.500          82           4
4          1430  2021-09-24 09:00:02.600          81           3
...         ...                      ...         ...         ...
13225      1430  2021-09-24 09:59:58.300          81          14
13226      1430  2021-09-24 09:59:59.500          82          14
13227      1430  2021-09-24 09:59:59.800          81          14
13228      1430  2021-09-24 09:59:59.800          82          17
13229      1430  2021-09-24 09:59:59.900          81          17

[13230 rows x 4 columns]

In [7]:
df_tenp.rename(columns={"signalid": "SignalID", " timestamp": "Timestamp", " eventcode":"EventCode", "eventparam":"EventParam"}, inplace = True)

In [8]:
df_tenp['Timestamp'] = pd.to_datetime(df_tenp['Timestamp'])
start_time = df_tenp['Timestamp'].values[0]
end_time = start_time +  np.timedelta64(400,'s')

In [9]:
df_subset = df_tenp[(df_tenp['Timestamp'] >= start_time) & (df_tenp['Timestamp'] <= end_time)]

In [10]:
df_subset.head(5)

   SignalID               Timestamp  EventCode  EventParam
0      1430 2021-09-24 09:00:00.900         43           8
1      1430 2021-09-24 09:00:01.600         81          11
2      1430 2021-09-24 09:00:02.100         82           3
3      1430 2021-09-24 09:00:02.500         82           4
4      1430 2021-09-24 09:00:02.600         81           3

In [12]:
time_plan, counts_df = process_data(df_subset.copy(), start_time, end_time)

In [11]:
def process_data(df2, start_time, end_time):
    
    df2.set_index('Timestamp', inplace = True)


    df2['t'] = df2.index
 
    df3 = df2[df2['EventCode'].isin([81])]
    df6 = df2[df2['EventCode'].isin([1, 11])]
 
    current = set()
    stime_list = []
    etime_list = []
    start_time = ''
    end_time = ''
    lis_ = []
 
    ts = df6['t'][0]
 
    start_time = ts
 
    for row in df6.values:
        if (ts == row[3]):
            # print('a')
            if (row[1] == 1):
                # print('b')
                current.add(row[2])
            elif (row[1] == 11):
                # print('c')
                current.discard(row[2])
        else:
            temp = ','.join(map(str, current))
            # current = set()
            lis_.append(temp)
            ts = row[3]
            end_time = ts
            stime_list.append(start_time)
            etime_list.append(end_time)
            start_time = ts
            if (row[1] == 1):
                current.add(row[2])
            elif (row[1] == 11):
                current.discard(row[2])
    # n grams
    # print("Starting n-grams")
    grams = ngrams(lis_, 6)
    gramFreq = collections.Counter(grams)
 
    time_plan = pd.DataFrame(columns=['green_phases', 'start_time', 'end_time', 'plan_number'],
                             index=range(1, len(lis_) + 1))
    time_plan['green_phases'] = lis_
    time_plan['start_time'] = stime_list
    time_plan['end_time'] = etime_list
    
    
    
    
    
    list_res = []
    for channel in df3['EventParam'].unique():
       
        df4 = df3[df3['EventParam'] ==  channel]

#         start_time = str(df4.index[0])[:10] + ' ' +'00' + ':00:01'
#         end_time = str(df4.index[0])[:10] + ' ' + '23' + ':59:59'


        new_row = pd.Series(data={'SignalID':1, 'EventCode':81, 'EventParam':channel, 't':pd.to_datetime(start_time) }, name=pd.to_datetime(start_time))
        df4 = df4.append(new_row, ignore_index=False)


        new_row = pd.Series(data={'SignalID':1, 'EventCode':81, 'EventParam':channel, 't':pd.to_datetime(end_time)  }, name=pd.to_datetime(end_time))
        df4 = df4.append(new_row, ignore_index=False)
        
        
        df4.sort_index(inplace = True)
       






        df4= df4.resample('5s').count()
        df4['time'] =df4.index.values
        df4 = df4[['EventParam','time']]
        
        df8 = pd.merge_asof(df4, time_plan, left_on='Timestamp', right_on='start_time')
        df8 = df8[['time','EventParam','green_phases']]
        df8.columns = ['time','count', 'green_phases']
        df8['detector_channel'] = channel
        list_res.append(df8)

    counts_df  = pd.concat(list_res)
    counts_df = counts_df.dropna()


    counts_df= counts_df[['time','count','green_phases','detector_channel']]
    
    
    
    return time_plan, counts_df